

chezmark_alias k kubectl
chezmark_alias kl "kubectl --context ifed-lab"
chezmark_alias kd "kubectl --context ifed-dev"
chezmark_alias kp "kubectl --context ifed"
chezmark_alias ke "kubectl --context ifed-exam"
chezmark_alias kedu "kubectl --context edusupport"

#alias kd='kubectl --context dev'
#alias kt='kubectl --context tst'
#alias ks='kubectl --context stg'
#alias ka='kubectl --context acc'
#alias kp='kubectl --context prd'
