

_chezmark_alias k kubectl
_chezmark_alias kl "kubectl --context ifed-lab"
_chezmark_alias kd "kubectl --context ifed-dev"
_chezmark_alias kp "kubectl --context ifed"
_chezmark_alias ke "kubectl --context ifed-exam"
_chezmark_alias kedu "kubectl --context edusupport"

#alias kd='kubectl --context dev'
#alias kt='kubectl --context tst'
#alias ks='kubectl --context stg'
#alias ka='kubectl --context acc'
#alias kp='kubectl --context prd'
