

_chez_alias k kubectl
_chez_alias kl "kubectl --context ifed-lab"
_chez_alias kd "kubectl --context ifed-dev"
_chez_alias kp "kubectl --context ifed"
_chez_alias ke "kubectl --context ifed-exam"
_chez_alias kedu "kubectl --context edusupport"

#alias kd='kubectl --context dev'
#alias kt='kubectl --context tst'
#alias ks='kubectl --context stg'
#alias ka='kubectl --context acc'
#alias kp='kubectl --context prd'
