font_size 20
tab_bar_edge top
tab_bar_style powerline
# tab_powerline_style slanted
enable_audio_bell no

## Mouse behavior
copy_on_select yes
strip_trailing_spaces smart
mouse_map shift+right press ungrabbed mouse_selection extend
mouse_map right press ungrabbed paste_from_selection


shell fish
editor hx
allow_remote_control yes


kitty_mod ctrl+shift

map ctrl+page_down next_tab
map ctrl+page_up previous_tab

# https://sw.kovidgoyal.net/kitty/faq/#how-do-i-open-a-new-window-or-tab-with-the-same-working-directory-as-the-current-window
map ctrl+shift+n launch --cwd=current --type=os-window
map ctrl+shift+t launch --cwd=current --type=tab
map ctrl+shift+p launch --cwd=current

# map super+c send_text all copy_to_clipboard
# map super+v send_text all paste_from_clipboard

map ctrl+v kitten kitty_grab/grab.py
